/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:0e3cd7c39ff9b1c0c5da04536e3094d0:22b4c217d5d07f252f16651258a2e32b:5e114c05734accc95cf72900a150fbb9$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string ClearSprite = "ClearSprite";
		public const string Tile_CheapConcrete = "Tile_CheapConcrete";
		public const string Tile_Dirt = "Tile_Dirt";
		public const string Tile_Grass = "Tile_Grass";
		public const string Tile_Sand = "Tile_Sand";
		public const string Wall_Basic_Cross = "Wall_Basic_Cross";
		public const string Wall_Basic_East_Ending = "Wall_Basic_East_Ending";
		public const string Wall_Basic_Horizontal = "Wall_Basic_Horizontal";
		public const string Wall_Basic_L_East_South = "Wall_Basic_L_East_South";
		public const string Wall_Basic_L_North_East = "Wall_Basic_L_North_East";
		public const string Wall_Basic_L_North_West = "Wall_Basic_L_North_West";
		public const string Wall_Basic_L_South_West = "Wall_Basic_L_South_West";
		public const string Wall_Basic_North_Ending = "Wall_Basic_North_Ending";
		public const string Wall_Basic_South_Ending = "Wall_Basic_South_Ending";
		public const string Wall_Basic_T_East_South_West = "Wall_Basic_T_East_South_West";
		public const string Wall_Basic_T_North_East_South = "Wall_Basic_T_North_East_South";
		public const string Wall_Basic_T_North_East_West = "Wall_Basic_T_North_East_West";
		public const string Wall_Basic_T_North_South_West = "Wall_Basic_T_North_South_West";
		public const string Wall_Basic_Vertical = "Wall_Basic_Vertical";
		public const string Wall_Basic_West_Ending = "Wall_Basic_West_Ending";
	}
}